---
- name: Install Brave Browser
  hosts: all
  become: true
  tags:
    - brave
    - install

  tasks:
    - name: Check the OS type
      ansible.builtin.setup:
      tags: always

    - name: Install required libraries on Debian-based Linux
      apt:
        name: 
          - curl
          - apt-transport-https
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Homebrew on macOS
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Brave Browser on macOS
      homebrew:
        name: brave-browser
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Download Brave Browser archive-keyring.gpg on Debian-based Linux
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Brave Browser PPA on Debian-based Linux
      shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Brave Browser on Debian-based Linux
      apt:
        update_cache: yes
        name: brave-browser
      when: ansible_facts['os_family'] == "Debian"
