---
  - name: Install Zsh on Linux
      apt:
        name: zsh
        state: present
      when: ansible_os_family == "Debian"
      # Installs Zsh on Debian-based systems (like Linux Mint) using the apt package manager

    - name: Install Zsh on macOS
      homebrew:
        name: zsh
        state: present
      when: ansible_os_family == "Darwin"
      # Installs Zsh on macOS using the Homebrew package manager

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL {{ zsh_install_script }})"
      args:
        creates: /home/{{ ansible_user_id }}/.oh-my-zsh
      # Downloads and runs the Oh My Zsh installation script if not already installed

    - name: Set Zsh as default shell on Linux
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      when: ansible_os_family == "Debian"
      # Sets Zsh as the default shell for the current user on Debian-based systems

    - name: Set Zsh as default shell on macOS
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/local/bin/zsh
      when: ansible_os_family == "Darwin"
      # Sets Zsh as the default shell for the current user on macOS

    - name: Install Starship on Linux
      shell: curl -fsSL {{ starship_install_script }} | bash -s -- --yes
      args:
        creates: /usr/local/bin/starship
      when: ansible_os_family == "Debian"
      # Downloads and installs Starship on Debian-based systems

    - name: Install Starship on macOS
      shell: curl -fsSL {{ starship_install_script }} | bash -s -- --yes
      args:
        creates: /usr/local/bin/starship
      when: ansible_os_family == "Darwin"
      # Downloads and installs Starship on macOS

    - name: Ensure .zshrc exists
      file:
        path: /home/{{ ansible_user_id }}/.zshrc
        state: touch
      # Ensures the .zshrc file exists

    - name: Configure Starship for Zsh
      lineinfile:
        path: /home/{{ ansible_user_id }}/.zshrc
        line: 'eval "$(starship init zsh)"'
        state: present
      # Adds the Starship initialization command to the .zshrc file